name: Backup 
on:
  schedule:
    - cron:  '43 0 * * *'
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Download-main-site
         run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent 'queercare.network' -e robots=off -N --reject-regex "\?" ||true
       - name: Download-wiki
         run: wget --mirror --convert-links --adjust-extension --page-requisites --no-parent wget -r --reject-regex "(\?|Special)" 'wiki.queercare.network' -e robots=off ||true
       - name: Commit results back
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
           commit_message: 'backed website'
